name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  deploy-flutter-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup and Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Flutter Dependencies
        working-directory: ./flutter_frontend_connect
        run: flutter pub get

      - name: Run Static Code Analysis
        working-directory: ./flutter_frontend_connect
        run: flutter analyze

      - name: Run Flutter Tests
        working-directory: ./flutter_frontend_connect
        run: flutter test

  lint-python-backend:
    name: Lint Python Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest
          
      - name: Run Python Linter (Pylint)
        run: pylint .
        working-directory: ./backend
      - name: Run Python Tests (pytest)
        run: pytest
        working-directory: ./backend

